url: 'http://localhost:3000'

mongodb:
  server:   localhost
  database: monitorDB
  user:     root 
  password:
  connectionString: mongodb+srv://aliyasir04:aliyasir04@monitordb-dqfyd.mongodb.net/test?retryWrites=true&w=majority

monitor:
  name:                   origin
  apiUrl:                 'http://localhost:3000/api' 
  pollingInterval:        5000      # five seconds
  timeout:                5000       # five seconds
  userAgent:              

autoStartMonitor: true

plugins:
  - ./plugins/console
  - ./plugins/email
  - ./plugins/basicAuth

email:
  method:      'SMTP'
  transport:         
    service:   'gmail' 
    auth:            
      user:   'aliyasir.04@gmail.com'
      pass:    'Zohaan@0903'
  event:
    up:        true
    down:      true
    paused:    false
    restarted: false
  message:           
    from:     'Ali <aliyasir.04@gmail.com>'
    to:     'aliyasir.04@gmail.com'

basicAuth:
  username:    aliyasir04
  password:    aliyasir04
verbose: false 

